### PR TITLE
initial contribution

### PR DESCRIPTION
**Pull request by t1**

### CODE REVIEW

**Comment by t1** [comment]
@jmartisk : please also check for the correct usage of the SmallRye brand.

**Comment by jmartisk** [comment]
Thanks! I'll check it but give me a few days, I'm a little busy, and this is not something that I'm familiar with...

**Comment by jmartisk** [comment]
@t1 I'm trying it and am having some issues, I pinged you on Zulip, so please have a look there when you get some time

**Comment by jmartisk** [comment]
It worked for me in the end. This is absolutely awesome, thanks! 
Let's follow up with the necessary steps towards properly releasing and publishing

**Pull request merged**
